/**
 * layout.jsx
 */

import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/Nav/MainNav";
import Footer from "@/components/Footer/Footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("", inter.className)}>
        <MainNav />
        {children}
        <Footer  />
      </body>
    </html>
  );
}
